# Generated by Django 3.2.3 on 2021-06-26 23:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnoticia', models.UUIDField(default=uuid.uuid4, verbose_name='id')),
                ('titulo', models.CharField(max_length=80, verbose_name='titulo')),
                ('informacion', models.TextField(verbose_name='info')),
                ('imagen', models.ImageField(upload_to='media', verbose_name='imagen')),
                ('fuente', models.URLField(max_length=400, verbose_name='fuente')),
            ],
        ),
    ]
