# Generated by Django 3.2.3 on 2021-06-27 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticia',
            new_name='NoticiaOtrasFuentes',
        ),
    ]
