# Generated by Django 3.2.3 on 2021-07-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rut', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='rut')),
                ('foto', models.ImageField(upload_to='media', verbose_name='imagen')),
                ('nombre', models.CharField(max_length=200, verbose_name='titulo')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('pais', models.CharField(max_length=80, verbose_name='pais')),
            ],
        ),
    ]
