# Generated by Django 3.2.3 on 2021-07-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='contra',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='pass'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
    ]
