# Generated by Django 3.2.3 on 2021-06-27 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_noticia_noticiaotrasfuentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiaotrasfuentes',
            name='informacion',
        ),
    ]
