# Generated by Django 3.2.3 on 2021-06-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_noticiacarrusel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiacarrusel',
            name='fuente',
        ),
    ]
