# Generated by Django 3.2.3 on 2021-06-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_noticiacarrusel_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoticiaCarrusel',
            new_name='NoticiaDeportes',
        ),
    ]
